### ISSUE TITLE
401 Unauthorized when trying to install 

### ISSUE THREAD

**Issue by CristianPupazan** [rolodato/gitlab-letsencrypt#32]
I get the following when I try to install:

```
npm install -g gitlab-letsencrypt
npm ERR! code E401
npm ERR! 404 401 Unauthorized: le-acme-core@https://git.daplie.com/rolodato/le-acme-core/repository/archive.tar.gz

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-21T09_15_11_291Z-debug.log
```

`npm version: '5.5.1'.`

Here is the full content of the npm log:

```
cat /root/.npm/_logs/2017-11-21T09_15_11_291Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'gitlab-letsencrypt' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose npm-session 602561a04a184f18
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/gitlab-letsencrypt 505ms (from cache)
8 silly pacote tag manifest for gitlab-letsencrypt@latest fetched in 530ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule gitlab-letsencrypt@2.1.3 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/bluebird 68ms (from cache)
15 silly pacote version manifest for bluebird@3.5.0 fetched in 107ms
16 silly resolveWithNewModule bluebird@3.5.0 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/ms 118ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/node-forge 117ms (from cache)
19 http fetch GET 304 https://registry.npmjs.org/request-promise 114ms (from cache)
20 http fetch GET 304 https://registry.npmjs.org/request 116ms (from cache)
21 http fetch GET 304 https://registry.npmjs.org/xtend 116ms (from cache)
22 http fetch GET 304 https://registry.npmjs.org/yargs 116ms (from cache)
23 silly pacote version manifest for ms@2.0.0 fetched in 125ms
24 silly resolveWithNewModule ms@2.0.0 checking installable status
25 silly pacote version manifest for node-forge@0.7.1 fetched in 124ms
26 silly resolveWithNewModule node-forge@0.7.1 checking installable status
27 silly pacote version manifest for request-promise@4.2.1 fetched in 121ms
28 silly resolveWithNewModule request-promise@4.2.1 checking installable status
29 silly pacote version manifest for request@2.81.0 fetched in 123ms
30 silly resolveWithNewModule request@2.81.0 checking installable status
31 silly pacote version manifest for xtend@4.0.1 fetched in 122ms
32 silly resolveWithNewModule xtend@4.0.1 checking installable status
33 silly pacote version manifest for yargs@8.0.1 fetched in 122ms
34 silly resolveWithNewModule yargs@8.0.1 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/rsa-compat 140ms (from cache)
36 silly pacote version manifest for rsa-compat@1.2.7 fetched in 141ms
37 silly resolveWithNewModule rsa-compat@1.2.7 checking installable status
38 http fetch GET 401 https://git.daplie.com/rolodato/le-acme-core/repository/archive.tar.gz 654ms
39 silly fetchPackageMetaData error for le-acme-core@https://git.daplie.com/rolodato/le-acme-core/repository/archive.tar.gz 401 Unauthorized: le-acme-core@https://git.daplie.com/rolodato/le-acme-core/repository/archive.tar.gz
40 verbose stack Error: 401 Unauthorized: le-acme-core@https://git.daplie.com/rolodato/le-acme-core/repository/archive.tar.gz
40 verbose stack     at fetch.then.res (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
40 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
40 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
40 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
40 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
40 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
40 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
40 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
40 verbose stack     at Immediate.Async.drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
40 verbose stack     at runCallback (timers.js:789:20)
40 verbose stack     at tryOnImmediate (timers.js:751:5)
40 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
41 verbose cwd /
42 verbose Linux 4.9.44-linuxkit-aufs
43 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "gitlab-letsencrypt"
44 verbose node v8.9.1
45 verbose npm  v5.5.1
46 error code E401
47 error 404 401 Unauthorized: le-acme-core@https://git.daplie.com/rolodato/le-acme-core/repository/archive.tar.gz
48 verbose exit [ 1, true ]
```

Looks like the repository where le-acme-core is hosted requires auth all of the sudden.
Tried this both on ubuntu and mac-os.

**Comment by rolodato** [comment]
Hey @CristianPupazan, thanks for reporting this. Apparently my fork of `le-acme-core` hosted on git.daplie.com was forcefully set to private, most likely because the upstream repository was set to private as well (https://git.daplie.com/Daplie/le-acme-core returns 404).

As a workaround I've removed the fork relationship from the parent repository and set my fork to public, so you should be able to install it now. I'll leave this issue open until we figure out what happened and remove the dependency on my fork.

**Comment by rolodato** [comment]
git.daplie.com doesn't exist anymore, and it's not ever coming back. :(

In any case, le-acme-core now points to a repository on GitHub under my profile. This isn't ideal and I'm following up with Daplie to see if it can be restored, but for now there's nothing else we can do.
