### ISSUE TITLE
Syntax error on run

### ISSUE THREAD

**Issue by comfysquirrel** [rolodato/gitlab-letsencrypt#4]
This happens when running `gitlab-le`:

```
/usr/local/lib/node_modules/gitlab-letsencrypt/index.js:24
const reduceSequential = (reducer, initialValue, accum = initialValue) => (promiseFns) => {
                                                       ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by rolodato** [comment]
Which node version are you running?

**Comment by comfysquirrel** [comment]
4.4.4

**Comment by rolodato** [comment]
You'll have to run Node 6.x or use babel. I'll add a minimum engine requirement to the `package.json`.
